apiVersion: batch/v1
kind: Job
metadata:
  name: kuzora-database-migrate-job
spec:
  template:
    spec:
      containers:
      - name: kuzora-database-migrate
        image: gkuzora/transaction-service:latest
        command: ["poetry", "run", "alembic", "upgrade", "head"]
      restartPolicy: Never
  backoffLimit: 4
  activeDeadlineSeconds: 120
