"""add User.vector

Revision ID: e1369f771946
Revises: 4e7f4a00d63f
Create Date: 2024-08-18 12:04:53.963741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1369f771946'
down_revision: Union[str, None] = '4e7f4a00d63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vector', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vector')
    # ### end Alembic commands ###
