postgres:
  pg_dns: "postgresql+psycopg2://username:password@postgres-service:5432/gkuzora"
  pool_size: 10
  max_overflow: 20
tracing:
  enabled: True
  sampler_type: "const"
  sampler_param: 1
  agent_host: "jaeger"
  agent_port: 6831
  service_name: "transacton-service"
  logging: true
  validation: true
redis:
  host: "redis"
  port: 6379
  decode_responses: True
