version: "3"

services:
  app:
    container_name: "transaction-service-kuzora"
    build:
      context: app/
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "28081:8080"
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      - PYTHONPATH=/workspace/src
      - CONFIG_PATH=/workspace/src/config/config-local.yml
  db:
    image: postgres:16.3
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=mydatabase
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - dev-db-storage:/var/lib/postgresql/data
  redis:
    image: redis:7.4.0
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - dev-cache-storage:/root/redis
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
volumes:
  dev-db-storage:
  dev-cache-storage:
